os: osx
language: objective-c
osx_image: xcode8.3
node_js: *node

before_install:
  - cd server

install:
  - npm install
  - brew cask install phantomjs

script:
  - npm run build-server
  - npm run build-client

  - npm run test-local
  - npm run test-browser-phantom
  
